Adding an health check step.

diff --git a/.github/workflows/fastapi_deploy.yml b/.github/workflows/fastapi_deploy.yml
--- a/.github/workflows/fastapi_deploy.yml
+++ b/.github/workflows/fastapi_deploy.yml
@@ -37,3 +37,15 @@ jobs:
         shell: bash -l {0}  # Required to ensure the environment is activated
         run: |
           nohup python main.py &
+
+  Health-Check:
+    needs: Deploying-FastAPI:
+      runs-on: ubuntu-latest
+     
+      steps:
+        - name: Running Health Checks on the App
+          run: |
+            for i in {1..10}; do curl -s -o /dev/null -w "%{http_code}"  $HEALTHCHECK_URL | grep "200" && echo "Health check passed successfully" && exit 0|| echo "Waiting for service ...";
+              sleep 5;
+            done;
+            echo "Health check failed ***" && exit 1
